safetynet:
  pathFile: "src/main/java/com/safety/safetyNet/data/data.json"
server:
  port: 9000
logging:
  path: logs
  file:
    max-size: 1MB
    name: ${logging.path}/SafetyNet.log
  level:
    root: ERROR
    org:
      springframework:
        web: ERROR
    com:
      safety:
        safetyNet:
          repository: ERROR
          filter: INFO
          service: INFO
          controller: INFO
          SafetyNetApplication: ERROR
  pattern:
    console: "%red(%d{dd/MM/yyyy}) %highlight(%-5level) [%blue(%t)] %yellow(%C{1.}): %msg%n%throwable"
    file: "%n%d{dd/MM/yyyy HH:MM:ss} %p %C{1.}%n %m%n"
spring.main.banner-mode: off

---
spring.config.activate.on-profile: test
safetynet.pathFile: "src/test/java/com/safety/safetyNet/data/dataTest.json"
logging:
  path: logs
  file:
    max-size: 1MB
    name: ${logging.path}/SafetyNetTest.log
  level:
    root: ERROR
    org:
      springframework:
        web: ERROR
      boot:
        StartupInfoLogger: ERROR
    com:
      safety:
        safetyNet:
          service: DEBUG
          filter: INFO
---

management.endpoints.web.exposure.include: "*"

spring:
    mvc:
      pathmatch:
        matching-strategy: ant_path_matcher
    main:
      banner-mode: off
management:
  endpoints:
    web:
      exposure:
        include: "*"

